name: Deploy to Firebase
on:
  push:
    branches: [master]  # O "main" según tu repositorio
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build  # Si tu app requiere build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: edu-prov1.firebaseapp.com  # Reemplaza con tu ID de proyecto
          siteId: edu-prov1  # O "r-play" para la otra app
